# .readthedocs.yaml
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

# If your Sphinx conf.py is in module_4/docs/source/conf.py (typical)
sphinx:
  configuration: module_4/docs/source/conf.py

python:
  install:
    - requirements: module_4/requirements.txt
